import type { Metadata } from 'next';
import { Roboto_Condensed } from 'next/font/google';
import './globals.css';

const robotoSans = Roboto_Condensed({
  variable: '--font-roboto-sans',
  subsets: ['latin', 'cyrillic'],
});

export const metadata: Metadata = {
  title: 'FinanceApp',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoSans.variable} antialiased`}>
        <div className="bg-linear-to-b from-[blue]/20 from-[1px] to-[white] to-[1px] bg-size-[auto_20px]">
        <span className="absolute bg-pink-400/50 w-0.5 h-full left-[95px]"></span>
          <div className="flex flex-col w-full h-screen p-10 justify-center items-center bg-linear-to-r from-[blue]/20 from-[1px] to-[white]/0 to-[1px] bg-size-[20px]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
